### ISSUE TITLE
array key not found

### ISSUE THREAD

**Issue by sugenganthos** [bennvan/dokuwiki-plugin-latexcaption#1]
I found several error (when debug active): Array key undefned:

I suggest not using `list($matches, $label) = explode('|', $match, 2);` for array which some element may not exist. Here I change the code becomes:
```php
$matchArr = explode('|', $match, 2);
 //var_dump($matchArr);
 //list($matches, $label) = explode('|', $match, 2);
$matches = $matchArr[0];
if(count($matchArr) === 2){
	$label = $matchArr[1];
 }else{
	$label = '';
}
```

Also I spot some typo: `if (!$this->$helper)` Should be `if (!$this->helper)`

I hope this helps. Thank you

Here my version. 
[caption - Salin.txt](https://github.com/bennvan/dokuwiki-plugin-latexcaption/files/9948139/caption.-.Salin.txt)

**Comment by sugenganthos** [comment]
Also I found similar error from original Caption plugin

**Comment by bennvan** [comment]
Appreciate the input and will fix this shortly. Are you in fact using this plugin?

**Comment by sugenganthos** [comment]
Yes, of course. Since i use it on development pc, the debug, warning, and error messages all shown up

**Comment by bennvan** [comment]
I see.. What template are you using with it and is all other behaviour as intended?

**Comment by sugenganthos** [comment]
I use newspaper template.
I think all other behaviour is done good until now. But i'm not using it's other many function yet.

**Comment by bennvan** [comment]
Ok, thank you for the feedback. I had not tested the plugin beyond my own needs.
